---
- hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'protoc --version'
      ansible.builtin.command: /usr/local/bin/protoc --version
      changed_when: false
      register: protoc_test_output
    - name: Output from 'protoc --version'
      ansible.builtin.debug:
        msg: '{{ protoc_test_output.stdout }}'
