---
- name: Resolve platform specific vars
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: Look for install in {{ protoc_install_dir }}
  become: true
  ansible.builtin.stat:
    path: '{{ protoc_install_dir }}'
  changed_when: false
  register: protoc_binary
- name: Downloading and installing protobuf tools
  when: not protoc_binary.stat.exists
  block:
    - name: Downloading {{ protoc_url }} to {{ protoc_tmp_zip }}
      become: true
      become_user: root
      ansible.builtin.get_url:
        url: '{{ protoc_url }}'
        dest: '{{ protoc_tmp_zip }}'
        checksum: '{{ protoc_checksum }}'
        mode: '644'
    - name: Mkdir {{ protoc_install_dir }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ protoc_install_dir }}'
        state: directory
        mode: '755'
    - name: Installing andrewrothstein.unarchivedeps
      ansible.builtin.include_role:
        name: andrewrothstein.unarchivedeps
    - name: Unarchiving {{ protoc_tmp_zip }}
      become: true
      become_user: root
      ansible.builtin.unarchive:
        remote_src: true
        src: '{{ protoc_tmp_zip }}'
        dest: '{{ protoc_install_dir }}'
        creates: '{{ protoc_install_dir }}/bin/protoc'
  always:
    - name: Rm {{ protoc_tmp_zip }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ protoc_tmp_zip }}'
        state: absent
- name: Mark executables/directories as executable/readable
  become: true
  become_user: root
  with_items:
    - p: '{{ protoc_install_dir }}/bin'
      t: directory
    - p: '{{ protoc_install_dir }}/include'
      t: directory
    - p: '{{ protoc_install_dir }}/bin/protoc'
      t: file
  ansible.builtin.file:
    path: '{{ item.p }}'
    mode: '755'
    state: '{{ item.t }}'
- name: Link executables...
  become: true
  become_user: root
  with_items:
    - protoc
  ansible.builtin.file:
    src: '{{ protoc_install_dir }}/bin/{{ item }}'
    dest: '{{ protoc_parent_install_dir }}/bin/{{ item }}'
    state: link
